### ISSUE TITLE
EmptySet should not be an instance

### ISSUE THREAD

**Issue by kbuzzard** [Hop311/M4R#1]
https://github.com/Hop311/M4R/blob/a27cfbb88a88bc6c7c1e498889e161c0e2b0bc00/M4R/Set/Basic.lean#L10

`Set` is not a class, so `EmptySet : Set α` should not be an instance -- nothing will change it if you make it `def`.

**Comment by Hop311** [comment]
I've removed EmptySet entirely, as Set.Empty already provides an empty set def
